{"level":"info","message":"Server is running on port 3000"}
{"level":"error","message":"Database connection failed:","name":"SequelizeConnectionRefusedError","original":{"code":"ECONNREFUSED"},"parent":{"code":"ECONNREFUSED"},"stack":"SequelizeConnectionRefusedError\n    at Client._connectionCallback (D:\\Desktop\\Code\\github\\mio-track\\node_modules\\.pnpm\\sequelize@6.37.5_pg@8.13.1\\node_modules\\sequelize\\lib\\dialects\\postgres\\connection-manager.js:133:24)\n    at Client._handleErrorWhileConnecting (D:\\Desktop\\Code\\github\\mio-track\\node_modules\\.pnpm\\pg@8.13.1\\node_modules\\pg\\lib\\client.js:326:19)\n    at Client._handleErrorEvent (D:\\Desktop\\Code\\github\\mio-track\\node_modules\\.pnpm\\pg@8.13.1\\node_modules\\pg\\lib\\client.js:336:19)\n    at Connection.emit (node:events:519:28)\n    at Socket.reportStreamError (D:\\Desktop\\Code\\github\\mio-track\\node_modules\\.pnpm\\pg@8.13.1\\node_modules\\pg\\lib\\connection.js:57:12)\n    at Socket.emit (node:events:519:28)\n    at emitErrorNT (node:internal/streams/destroy:169:8)\n    at emitErrorCloseNT (node:internal/streams/destroy:128:3)\n    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)"}
{"level":"info","message":"Server is running on port 3000"}
{"level":"error","message":"Database connection failed:","name":"SequelizeConnectionRefusedError","original":{"code":"ECONNREFUSED"},"parent":{"code":"ECONNREFUSED"},"stack":"SequelizeConnectionRefusedError\n    at Client._connectionCallback (D:\\Desktop\\Code\\github\\mio-track\\node_modules\\.pnpm\\sequelize@6.37.5_pg@8.13.1\\node_modules\\sequelize\\lib\\dialects\\postgres\\connection-manager.js:133:24)\n    at Client._handleErrorWhileConnecting (D:\\Desktop\\Code\\github\\mio-track\\node_modules\\.pnpm\\pg@8.13.1\\node_modules\\pg\\lib\\client.js:326:19)\n    at Client._handleErrorEvent (D:\\Desktop\\Code\\github\\mio-track\\node_modules\\.pnpm\\pg@8.13.1\\node_modules\\pg\\lib\\client.js:336:19)\n    at Connection.emit (node:events:519:28)\n    at Socket.reportStreamError (D:\\Desktop\\Code\\github\\mio-track\\node_modules\\.pnpm\\pg@8.13.1\\node_modules\\pg\\lib\\connection.js:57:12)\n    at Socket.emit (node:events:519:28)\n    at emitErrorNT (node:internal/streams/destroy:169:8)\n    at emitErrorCloseNT (node:internal/streams/destroy:128:3)\n    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)"}
